#!/usr/bin/env bash

#
# Post processing hotfix branch creation.
#

VERSION=${1:1}

SCRIPT_PATH="$0"; while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
. "$(dirname $SCRIPT_PATH)/modules/functions.sh"

# Checkout to new hotfix branch and update versions for new version.
git checkout hotfix/$VERSION
. "$HOOKS_DIR/modules/update_versions.sh" $VERSION-SNAPSHOT

exit 0