#!/usr/bin/env bash

#
# Prepare repository for release.
#

VERSION=${1:1}

SCRIPT_PATH="$0"; while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
. "$(dirname $SCRIPT_PATH)/modules/functions.sh"

# Checkout to develop branch and update project version to new version.
# It is required for avoid version merge conflicts in a future.

git checkout develop
. "$HOOKS_DIR/modules/update_versions.sh" $VERSION-SNAPSHOT

exit 0