#!/usr/bin/env bash

#
# Build project on release branch and prepare for release.
#

VERSION=${1:1}

SCRIPT_PATH="$0"; while [ -h "$SCRIPT_PATH" ]; do SCRIPT_PATH=$(readlink "$SCRIPT_PATH"); done
. "$(dirname $SCRIPT_PATH)/modules/functions.sh"

# Checkout to release branch and build project update version to release non snapshot version.
git checkout release/$VERSION
. "$HOOKS_DIR/modules/update_versions.sh" $VERSION

# Next build project. If you want to modify build process edit the following line.
mvn clean verify

if [ $? -ne 0 ]; then
    # Check build status. If build failed break down gitflow process.
	echo Build failed. Abort.
	exit 1
fi

# Checkout to develop branch and update version for current version.
# It is needed for avoid merge conflicts in a future.
git checkout develop
. "$HOOKS_DIR/modules/update_versions.sh" $VERSION

# Checkout back to release branch.
git checkout release/$VERSION

exit 0